# This file is auto-generated by @hey-api/openapi-python

from enum import Enum
from typing import Annotated, Optional, TypeAlias

from pydantic import BaseModel, EmailStr, Field, RootModel


class AuthInfo(BaseModel):
    email: EmailStr
    password: str


class BadRequestError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class ConflictError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class Course(BaseModel):
    id: int
    name: str
    description: str


class CourseCreateDto(BaseModel):
    name: Annotated[str, Field(min_length=1, max_length=200)]
    description: Annotated[str, Field(min_length=1)]


class CourseEditDto(BaseModel):
    name: Optional[Annotated[str, Field(min_length=1, max_length=200)]] = None
    description: Optional[Annotated[str, Field(min_length=1)]] = None


class CourseLesson(BaseModel):
    id: int
    course_id: int = Field(..., alias="courseId")
    name: str
    body: str


class CourseLessonCreateDto(BaseModel):
    name: Annotated[str, Field(min_length=1, max_length=200)]
    body: Annotated[str, Field(min_length=1)]


class CourseLessonEditDto(BaseModel):
    name: Optional[Annotated[str, Field(min_length=1, max_length=200)]] = None
    body: Optional[Annotated[str, Field(min_length=1)]] = None


class ForbiddenError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class NotFoundError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class PageMeta(BaseModel):
    """Где клиент находится и сколько всего есть. Без этого блока номер
    страницы уходит в запрос, а обратно не возвращается ничего: узнать,
    есть ли следующая страница, нельзя.
    """

    page: int
    per_page: int = Field(..., alias="perPage")
    total: int
    total_pages: int = Field(..., alias="totalPages")


class CourseLessonPage(BaseModel):
    data: list[CourseLesson]
    meta: PageMeta


class CoursePage(BaseModel):
    data: list[Course]
    meta: PageMeta


class PreconditionFailedError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class ProblemDetails(BaseModel):
    """https://www.rfc-editor.org/rfc/rfc9457.html"""

    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


ResourceId: TypeAlias = int


class TokenInfo(BaseModel):
    token: str


class TooManyRequestsError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class UnauthorizedError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None


class UnprocessableEntityErrorErrors(BaseModel):
    message: str
    rule: str
    field: str


class UnprocessableEntityError(BaseModel):
    type: Optional[str] = None
    title: Optional[str] = None
    status: Optional[int] = None
    detail: Optional[str] = None
    instance: Optional[str] = None
    errors: list[UnprocessableEntityErrorErrors]


class User(BaseModel):
    id: int
    full_name: Optional[Annotated[str, Field(min_length=2, max_length=100)]] = Field(default=None, alias="fullName")
    phone: Optional[str] = None
    email: EmailStr


class UserCreateDto(BaseModel):
    full_name: Optional[Annotated[str, Field(min_length=2, max_length=100)]] = Field(default=None, alias="fullName")
    email: EmailStr
    password: Annotated[str, Field(min_length=8)]
    phone: Optional[Annotated[str, Field(max_length=30)]] = None


class UserEditDto(BaseModel):
    full_name: Optional[Annotated[str, Field(min_length=2, max_length=100)]] = Field(default=None, alias="fullName")
    password: Optional[Annotated[str, Field(min_length=8)]] = None
    phone: Optional[Annotated[str, Field(max_length=30)]] = None


class UserPage(BaseModel):
    data: list[User]
    meta: PageMeta


class Versions(str, Enum):
    V1 = "v1"
    V2 = "v2"


class CoursesIndexQuery(BaseModel):
    page: Optional[Annotated[int, Field(ge=1, le=2147483647)]] = 1
    per_page: Optional[Annotated[int, Field(ge=1, le=100)]] = Field(default=10, alias="perPage")


class CoursesIndexResponse(RootModel[CoursePage]):
    """The request has succeeded."""

    root: CoursePage


class CoursesCreateBody(RootModel[CourseCreateDto]):
    root: CourseCreateDto


class CoursesCreateResponse(RootModel[Course]):
    """The request has succeeded and a new resource has been created as a result."""

    root: Course


class CoursesDestroyHeaders(BaseModel):
    if_match: Optional[str] = Field(default=None, alias="If-Match")


class CoursesDestroyPath(BaseModel):
    course_id: ResourceId


class CoursesDestroyResponse(RootModel[None]):
    """There is no content to send for this request, but the headers may be useful. """

    root: None


class CoursesShowPath(BaseModel):
    course_id: ResourceId


class CoursesShowResponse(RootModel[Course]):
    """The request has succeeded."""

    root: Course


class CoursesUpdateBody(RootModel[CourseEditDto]):
    root: CourseEditDto


class CoursesUpdateHeaders(BaseModel):
    if_match: Optional[str] = Field(default=None, alias="If-Match")


class CoursesUpdatePath(BaseModel):
    course_id: ResourceId


class CoursesUpdateResponse(RootModel[Course]):
    """The request has succeeded."""

    root: Course


class CoursesLessonsIndexPath(BaseModel):
    course_id: ResourceId


class CoursesLessonsIndexQuery(BaseModel):
    page: Optional[Annotated[int, Field(ge=1, le=2147483647)]] = 1
    per_page: Optional[Annotated[int, Field(ge=1, le=100)]] = Field(default=10, alias="perPage")


class CoursesLessonsIndexResponse(RootModel[CourseLessonPage]):
    """The request has succeeded."""

    root: CourseLessonPage


class CoursesLessonsCreateBody(RootModel[CourseLessonCreateDto]):
    root: CourseLessonCreateDto


class CoursesLessonsCreatePath(BaseModel):
    course_id: ResourceId


class CoursesLessonsCreateResponse(RootModel[CourseLesson]):
    """The request has succeeded and a new resource has been created as a result."""

    root: CourseLesson


class CoursesLessonsDestroyPath(BaseModel):
    course_id: ResourceId
    lesson_id: ResourceId


class CoursesLessonsDestroyResponse(RootModel[None]):
    """There is no content to send for this request, but the headers may be useful. """

    root: None


class CoursesLessonsShowPath(BaseModel):
    course_id: ResourceId
    lesson_id: ResourceId


class CoursesLessonsShowResponse(RootModel[CourseLesson]):
    """The request has succeeded."""

    root: CourseLesson


class CoursesLessonsUpdateBody(RootModel[CourseLessonEditDto]):
    root: CourseLessonEditDto


class CoursesLessonsUpdatePath(BaseModel):
    course_id: ResourceId
    lesson_id: ResourceId


class CoursesLessonsUpdateResponse(RootModel[CourseLesson]):
    """The request has succeeded."""

    root: CourseLesson


class TokensCreateBody(RootModel[AuthInfo]):
    root: AuthInfo


class TokensCreateResponse(RootModel[TokenInfo]):
    """The request has succeeded and a new resource has been created as a result."""

    root: TokenInfo


class UsersIndexQuery(BaseModel):
    page: Optional[Annotated[int, Field(ge=1, le=2147483647)]] = 1
    per_page: Optional[Annotated[int, Field(ge=1, le=100)]] = Field(default=10, alias="perPage")


class UsersIndexResponse(RootModel[UserPage]):
    """The request has succeeded."""

    root: UserPage


class UsersCreateBody(RootModel[UserCreateDto]):
    root: UserCreateDto


class UsersCreateResponse(RootModel[User]):
    """The request has succeeded and a new resource has been created as a result."""

    root: User


class UsersDestroyPath(BaseModel):
    user_id: ResourceId


class UsersDestroyResponse(RootModel[None]):
    """There is no content to send for this request, but the headers may be useful. """

    root: None


class UsersShowPath(BaseModel):
    user_id: ResourceId


class UsersShowResponse(RootModel[User]):
    """The request has succeeded."""

    root: User


class UsersUpdateBody(RootModel[UserEditDto]):
    root: UserEditDto


class UsersUpdatePath(BaseModel):
    user_id: ResourceId


class UsersUpdateResponse(RootModel[User]):
    """The request has succeeded."""

    root: User
